"""rework application status model

Revision ID: 21d6cae8aed5
Revises: abcee3148599
Create Date: 2026-06-18 23:14:24.753780
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '21d6cae8aed5'
down_revision: str | None = 'abcee3148599'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('status', sa.Enum('eligible', 'ineligible', name='applicationstatus'), nullable=False))
    op.add_column('applications', sa.Column('status_source', sa.Enum('untouched', 'rules', 'ai', 'human', name='statussource'), nullable=False))
    op.add_column('applications', sa.Column('reviewed_fingerprint', sa.String(length=64), nullable=True))
    op.drop_index(op.f('ix_applications_hard_filter_status'), table_name='applications')
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_status_source'), 'applications', ['status_source'], unique=False)
    op.drop_column('applications', 'hard_filter_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('hard_filter_status', sa.VARCHAR(length=12), nullable=False))
    op.drop_index(op.f('ix_applications_status_source'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.create_index(op.f('ix_applications_hard_filter_status'), 'applications', ['hard_filter_status'], unique=False)
    op.drop_column('applications', 'reviewed_fingerprint')
    op.drop_column('applications', 'status_source')
    op.drop_column('applications', 'status')
    # ### end Alembic commands ###

