"""add estimated_usd to run_cost_ledger

Revision ID: 3364cadf6ede
Revises: 9c0ee540ce8f
Create Date: 2026-07-16 21:55:14.943331
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '3364cadf6ede'
down_revision: str | None = '9c0ee540ce8f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_cost_ledger', sa.Column('estimated_usd', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_cost_ledger', 'estimated_usd')
    # ### end Alembic commands ###

