"""add sync_run unchanged_count

Revision ID: 3ac21f021182
Revises: 21d6cae8aed5
Create Date: 2026-06-19 00:19:22.932632
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3ac21f021182'
down_revision: str | None = '21d6cae8aed5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # server_default backfills existing rows so the NOT NULL add succeeds on a
    # populated table.
    op.add_column(
        'sync_runs',
        sa.Column('unchanged_count', sa.Integer(), nullable=False, server_default='0'),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_runs', 'unchanged_count')
    # ### end Alembic commands ###

