"""add feedback table (M15 in-app member→admin feedback channel)

Additive only: one new ``feedback`` table for the from-any-page feedback channel
(M15 "Future UX Enhancements" #2). A member submits free text; each row carries the
context they were in (route/active_tab/analysis_id — all nullable) plus server-stamped
identity (user_id FK), app_version, and timestamps. ``resolved_at`` (nullable) records
when an admin marked it handled; resolved items are retained, never deleted, so the
friction history survives. No backfill, no data touched. Downgrade drops the table
(lossy: existing feedback is discarded, acceptable for a brand-new additive table).
Back up the .db before running.

Revision ID: 4d135cde3491
Revises: c9d0e1f2a3b4
Create Date: 2026-07-24 17:35:50.661249
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '4d135cde3491'
down_revision: str | None = 'c9d0e1f2a3b4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('route', sa.String(length=500), nullable=True),
    sa.Column('active_tab', sa.String(length=100), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('app_version', sa.String(length=50), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###

