"""add prompt_version to application_ai_results

Revision ID: 6305b4e2d38b
Revises: 7cb3574a5aeb
Create Date: 2026-06-19 14:46:59.193321
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6305b4e2d38b'
down_revision: str | None = '7cb3574a5aeb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_ai_results', sa.Column('prompt_version', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_application_ai_results_prompt_version'), 'application_ai_results', ['prompt_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_ai_results_prompt_version'), table_name='application_ai_results')
    op.drop_column('application_ai_results', 'prompt_version')
    # ### end Alembic commands ###

