"""add feedback.applicant_id

Additive: one nullable ``applicant_id`` column on ``feedback``, capturing which applicant
detail page a member was on when they submitted (nullable — most feedback is from a list
or ranking, not a drill-in). No FK, matching ``analysis_id``: the id is kept for context
even if the applicant is later removed, and the admin view resolves the current name on
read (blank if gone). No backfill. Downgrade drops the column. Back up the .db first.

Revision ID: 725bae661bc1
Revises: 4d135cde3491
Create Date: 2026-07-24 17:50:03.163747
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '725bae661bc1'
down_revision: str | None = '4d135cde3491'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('applicant_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'applicant_id')
    # ### end Alembic commands ###

