"""run_cost_ledger

Revision ID: 7a35c155cb41
Revises: 2f0eebed8538
Create Date: 2026-07-07 23:39:02.395409
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7a35c155cb41'
down_revision: str | None = '2f0eebed8538'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_cost_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('fresh_usd', sa.Float(), nullable=False),
    sa.Column('cached_saved_usd', sa.Float(), nullable=False),
    sa.Column('passes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_cost_ledger_kind'), 'run_cost_ledger', ['kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_cost_ledger_kind'), table_name='run_cost_ledger')
    op.drop_table('run_cost_ledger')
    # ### end Alembic commands ###

