"""add dimension_aliases

Revision ID: 8c2b1295e691
Revises: 5d3446b2ca50
Create Date: 2026-07-11 18:00:42.008286
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8c2b1295e691'
down_revision: str | None = '5d3446b2ca50'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimension_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias_key', sa.String(length=200), nullable=False),
    sa.Column('canonical_key', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dimension_aliases_alias_key'), 'dimension_aliases', ['alias_key'], unique=True)
    op.create_index(op.f('ix_dimension_aliases_canonical_key'), 'dimension_aliases', ['canonical_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dimension_aliases_canonical_key'), table_name='dimension_aliases')
    op.drop_index(op.f('ix_dimension_aliases_alias_key'), table_name='dimension_aliases')
    op.drop_table('dimension_aliases')
    # ### end Alembic commands ###

